[build]
base  = "/"
publish = "site/rendered"
command = "chmod +x build.sh; ./build.sh"

# [[redirects]]
# from = "/*"
# to = "/404.html"
# status = 404

[[redirects]]
  from = "/fosstalks"
  to = "/events/fosstalks-2"
  status = 301
  force = true
